-- MySQL Script generated by MySQL Workbench
-- 05/03/18 22:10:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema finman
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `finman` ;

-- -----------------------------------------------------
-- Schema finman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finman` DEFAULT CHARACTER SET utf8 ;
USE `finman` ;

-- -----------------------------------------------------
-- Table `finman`.`stockitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finman`.`stockitem` ;

CREATE TABLE IF NOT EXISTS `finman`.`stockitem` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'The primary key of a stock item',
  `symbol` VARCHAR(45) NULL,
  `stockName` VARCHAR(64) NULL,
  `lastModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finman`.`portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finman`.`portfolio` ;

CREATE TABLE IF NOT EXISTS `finman`.`portfolio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `portfolioShortName` VARCHAR(45) NULL,
  `portfolioFullName` VARCHAR(45) NULL,
  `lastModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finman`.`portfolio_stockitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finman`.`portfolio_stockitem` ;

CREATE TABLE IF NOT EXISTS `finman`.`portfolio_stockitem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `portfolioID` INT NOT NULL,
  `stockItemID` INT NOT NULL,
  `purchaseDate` DATE NULL,
  `purchaseAmount` INT NULL,
  `purchasePrice` REAL NULL,
  PRIMARY KEY (`id`),
  INDEX `stockItemID_idx` (`stockItemID` ASC),
  INDEX `portfolioID_idx` (`portfolioID` ASC),
  CONSTRAINT `portfolio_stockitem_fkportfolio`
    FOREIGN KEY (`portfolioID`)
    REFERENCES `finman`.`portfolio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `portfolio_stockitem_fkstockitem`
    FOREIGN KEY (`stockItemID`)
    REFERENCES `finman`.`stockitem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finman`.`stockquote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finman`.`stockquote` ;

CREATE TABLE IF NOT EXISTS `finman`.`stockquote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stockItemID` INT NOT NULL,
  `priceDate` DATETIME NOT NULL,
  `priceOpen` REAL NULL,
  `priceHigh` REAL NULL,
  `priceLow` REAL NULL,
  `priceClose` REAL NULL,
  `tradeVolume` INT NULL,
  `lastModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `stockItemID_idx` (`stockItemID` ASC),
  CONSTRAINT `fkstockitem`
    FOREIGN KEY (`stockItemID`)
    REFERENCES `finman`.`stockitem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO finman;
 DROP USER finman;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'finman' IDENTIFIED BY 'finmanfidos';

GRANT SELECT, INSERT, TRIGGER ON TABLE `finman`.* TO 'finman';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `finman`.* TO 'finman';
GRANT ALL ON `finman`.* TO 'finman';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
